name: Barebone Crawler

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas gspread oauth2client gspread-formatting tenacity aiohttp
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        
    - name: Run all barebobe
      env:
          SITE_URL: ${{ secrets.SITE_URL }}
      run: python runallbarebone.py
