name: Barebone Crawler

on:
  schedule:
    - cron: '0 23,2,5,8,11 * * 1-6'
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas gspread oauth2client gspread-formatting tenacity aiohttp
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        
    - name: Run all barebobe
      env:
          SHEET_URL: ${{ secrets.SHEET_URL }}
          MK_WC_API_URL: ${{ secrets.MK_WC_API_URL }}
          MK_WC_CONSUMER_KEY: ${{ secrets.MK_WC_CONSUMER_KEY }}
          MK_WC_CONSUMER_SECRET: ${{ secrets.MK_WC_CONSUMER_SECRET }}
      run: python runallbarebone.py
